# Используем официальный образ Node.js для разработки
FROM node:22.12.0-alpine AS development

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json для установки зависимостей
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

RUN npm install -g nodemon

# Копируем все файлы проекта в контейнер
COPY . .

# Запускаем сервер в режиме разработки
CMD ["nodemon", "src/main.ts"]

# Открываем порт, на котором работает сервер
EXPOSE 3000